#!/bin/sh
# Regenerate notices for modules used by any supported platform.
set -eu
cd "$(dirname "$0")/.."
workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' 0
for target in darwin/arm64 darwin/amd64 linux/amd64 linux/arm64 windows/amd64 windows/arm64; do
    GOOS=${target%/*} GOARCH=${target#*/} go list -deps \
        -f '{{with .Module}}{{if not .Main}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}{{end}}' .
done > "$workdir/modules"
sort -u "$workdir/modules" > "$workdir/unique"
printf '# Third-party notices\n\nGenerated by `sh scripts/notices.sh` from dependencies used by supported builds.\n' > "$workdir/NOTICE.md"
while IFS='|' read -r module version directory; do
    [ -n "$module" ] || continue
    printf '\n## %s %s\n' "$module" "$version" >> "$workdir/NOTICE.md"
    found=false
    for license in "$directory"/LICENSE* "$directory"/LICENCE* "$directory"/COPYING* "$directory"/NOTICE*; do
        [ -f "$license" ] || continue
        found=true
        printf '\n### %s\n\n```text\n' "${license##*/}" >> "$workdir/NOTICE.md"
        cat "$license" >> "$workdir/NOTICE.md"
        printf '\n```\n' >> "$workdir/NOTICE.md"
    done
    if [ "$found" = false ]; then
        printf 'Missing license for %s\n' "$module" >&2
        exit 1
    fi
done < "$workdir/unique"
mv "$workdir/NOTICE.md" NOTICE.md
